name: Build executable

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      python-version: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with pyinstaller
        run: |
          pyinstaller --onefile --icon bin/logo.ico downloader.py
          cp README.md dist/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloader-${{ matrix.os }}-py${{ env.python-version }}
          path: |
            dist/
          retention-days: 30
